repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      language: python
      types: [python]
      args: ["--line-length=72"]
