---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: mixed-line-ending
            args: [--fix=lf]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/ambv/black
      rev: 23.3.0
      hooks:
          - id: black
            language: python
            types: [python]
            args: [--line-length=72]
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            name: isort (python)
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.1
      hooks:
          - id: prettier
            types_or: [scss, javascript, html]
