---
services:
    database:
        build:
            context: files/database
        restart: always
        healthcheck:
            test: [CMD-SHELL, pg_isready, -u, $POSTGRES_USER, -d, $POSTGRES_DB]
            interval: 15s
            timeout: 10s
            retries: 5
        volumes:
            - ./files/database/data:/data/db
        networks:
            - backnet
        env_file: files/database/.env
        expose:
            - 5438

    analyser:
        build:
            context: files/analyser
        restart: always
        healthcheck:
            test: curl --fail http://localhost:8080/alive || exit 1
            interval: 15s
            timeout: 10s
            retries: 5
        networks:
            - backnet
        env_file: files/analyser/.env
        expose:
            - 8080
        depends_on:
            db:
                condition: service_healthy

    website:
        build:
            context: files/website
        restart: always
        healthcheck:
            test: curl --fail http://localhost || exit 1
            interval: 15s
            timeout: 10s
            retries: 5
        networks:
            - backnet
            - outside
        env_file: files/website/.env
        ports:
            - 80:80
        depends_on:
            db:
                condition: service_healthy
            analyser:
                condition: service_healthy

networks:
    backnet:
    outside:
