---
services:
    db:
        build:
            context: db
        restart: always
        healthcheck:
            test: [CMD, mongosh, --eval, db.adminCommand('ping')]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 10s
        networks:
            - backnet
        env_file: db/.env
        expose:
            - 27017

    analyser:
        build:
            context: analyser
        restart: always
        healthcheck:
            test: curl --fail http://localhost:8080/alive || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 5s
        networks:
            - backnet
        env_file: analyser/.env
        expose:
            - 8080
        depends_on:
            db:
                condition: service_healthy

    website:
        build:
            context: audialytix
        restart: always
        healthcheck:
            test: curl --fail http://localhost || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 10s
        networks:
            - backnet
            - outside
        env_file: audialytix/.env
        ports:
            - 80:80
        depends_on:
            db:
                condition: service_healthy
            analyser:
                condition: service_healthy

networks:
    backnet:
    outside:
