# Generated by Django 4.1.10 on 2023-08-21 05:10

import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist", models.CharField(max_length=255)),
                ("song_name", models.CharField(max_length=255)),
                (
                    "audio_type",
                    models.CharField(
                        choices=[("stereo", "Stereo"), ("mono", "Mono")], max_length=10
                    ),
                ),
                ("audio_points", djongo.models.fields.JSONField()),
                (
                    "onset_analysis",
                    djongo.models.fields.JSONField(blank=True, null=True),
                ),
                (
                    "spectral_analysis",
                    djongo.models.fields.JSONField(blank=True, null=True),
                ),
            ],
        ),
    ]
