# Generated by Django 4.1.10 on 2023-08-24 04:08

import django.db.models.deletion
import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("error", models.CharField(blank=True, max_length=255, null=True)),
                ("author", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[("stereo", "Stereo"), ("mono", "Mono")], max_length=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnsetData",
            fields=[
                ("data", djongo.models.fields.JSONField()),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.audiofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpectralData",
            fields=[
                ("data", djongo.models.fields.JSONField()),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.audiofile",
                    ),
                ),
            ],
        ),
    ]
