# Generated by Django 4.1.10 on 2023-08-25 05:35
import json
import os
import os.path

from django.db import migrations

DIR_PATH = os.path.dirname(os.path.realpath(__file__))


class Migration(migrations.Migration):
    def create_audio_files(apps, schema_editor):
        AudioFile = apps.get_model("api", "AudioFile")
        OnsetData = apps.get_model("api", "OnsetData")
        SpectralData = apps.get_model("api", "SpectralData")

        def create_analysis(name, author, analysis_type, file_id):
            audio_file = AudioFile.objects.create(
                author=author,
                name=name,
                analysis_type=analysis_type,
            )

            with open(
                os.path.join(DIR_PATH, f"data/migration_{file_id}_onset_data.json"), "r"
            ) as F:
                data = json.load(F)
                OnsetData.objects.create(
                    file=audio_file,
                    data=data["data"],
                )

            with open(
                os.path.join(DIR_PATH, f"data/migration_{file_id}_spectral_data.json"),
                "r",
            ) as F:
                data = json.load(F)
                SpectralData.objects.create(
                    file=audio_file,
                    data=data["data"],
                )

        create_analysis("OutKast", "Hey Ya", "stereo", "outkast")

        create_analysis("Daft Punk", "One More time", "stereo", "daftpunk")

        create_analysis("Skepta", "Glow In The Dark", "mono", "skepta")

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_audio_files)]
